# Generated by Django 6.0.2 on 2026-03-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guns', '0006_stocklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='gun',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
