# Generated by Django 6.0.2 on 2026-03-31 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guns', '0007_gun_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockLog',
        ),
    ]
